name: holocron-analytics
services:
  initdb:
    command:
      - |
        set -e
        echo "Waiting for SQL Server to accept connections..."
        for i in {1..60}; do
          /opt/mssql-tools/bin/sqlcmd -S sql2025 -U sa -P "$${MSSQL_SA_PASSWORD}" -C -Q "SELECT 1" -b && break
          sleep 2
        done

        # Function to run SQL scripts from a directory
        run_scripts() {
          local dir="$$1"
          if [ -d "$${dir}" ]; then
            for script in "$${dir}"/*.sql; do
              if [ -f "$${script}" ]; then
                echo "Running $${script}..."
                /opt/mssql-tools/bin/sqlcmd -S sql2025 -U sa -P "$${MSSQL_SA_PASSWORD}" -C \
                  -d "$${DATABASE_NAME}" -i "$${script}"
              fi
            done
          fi
        }

        echo "=== Creating database if not exists ==="
        /opt/mssql-tools/bin/sqlcmd -S sql2025 -U sa -P "$${MSSQL_SA_PASSWORD}" -C \
          -v DATABASE_NAME="$${DATABASE_NAME}" \
          -i /init-db.sql

        echo "=== Running DDL scripts ==="
        run_scripts "/ddl/01_dimensions"
        run_scripts "/ddl/02_facts"
        run_scripts "/ddl/03_bridges"

        echo "=== Database initialization complete ==="
    container_name: holocron-initdb
    depends_on:
      sql2025:
        condition: service_healthy
        required: true
    entrypoint:
      - /bin/bash
      - -c
    environment:
      DATABASE_NAME: Holocron
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    image: mcr.microsoft.com/mssql-tools
    networks:
      default: null
    volumes:
      - type: bind
        source: W:\Git\holocron-analytics\docker\init-db.sql
        target: /init-db.sql
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: W:\Git\holocron-analytics\src\db\ddl
        target: /ddl
        read_only: true
        bind:
          create_host_path: true
  seed:
    build:
      context: W:\Git\holocron-analytics
      dockerfile: docker/Dockerfile.seed
    command:
      - /bin/bash
      - -c
      - |2
          if [ "$${SEED_SKIP}" = "true" ]; then
            echo "SEED_SKIP=true, skipping seed loader"
            exit 0
          fi
          python src/ingest/seed_loader.py --all --verbose --no-file-log
    container_name: holocron-seed
    depends_on:
      initdb:
        condition: service_completed_successfully
        required: true
    environment:
      SEED_SKIP: "false"
      SEED_SQLSERVER_DATABASE: Holocron
      SEED_SQLSERVER_DRIVER: ODBC Driver 18 for SQL Server
      SEED_SQLSERVER_HOST: sql2025
      SEED_SQLSERVER_PASSWORD: ${MSSQL_SA_PASSWORD}
      SEED_SQLSERVER_PORT: "1433"
      SEED_SQLSERVER_USER: sa
    networks:
      default: null
    volumes:
      - type: bind
        source: W:\Git\holocron-analytics\src
        target: /app/src
        read_only: true
        bind:
          create_host_path: true
  sql2025:
    container_name: sql2025
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    healthcheck:
      test:
        - CMD-SHELL
        - /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -C -Q "SELECT 1" -b
      timeout: 5s
      interval: 10s
      retries: 12
      start_period: 30s
    image: mcr.microsoft.com/mssql/server:2025-latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 1433
        published: "1433"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: mssql_data
        target: /var/opt/mssql
        volume: {}
networks:
  default:
    name: holocron-analytics_default
volumes:
  mssql_data:
    name: holocron-analytics_mssql_data
    driver: local


