"""
Unit tests for scripts/export_pr_prompts_and_reports.py

Tests cover pure-logic functions that have no external dependencies.
"""

import math
import sys
from pathlib import Path

import pytest

# Make the scripts directory importable
sys.path.insert(
    0,
    str(Path(__file__).parent.parent.parent / "scripts"),
)

import export_pr_prompts_and_reports as exp


# ---------------------------------------------------------------------------
# pad_width calculation (inline helper mirrors production logic)
# ---------------------------------------------------------------------------

def _pad_width(end: int) -> int:
    return max(3, math.floor(math.log10(end)) + 1)


@pytest.mark.unit
class TestPadWidth:
    def test_end_1_returns_3(self):
        assert _pad_width(1) == 3

    def test_end_50_returns_3(self):
        assert _pad_width(50) == 3

    def test_end_999_returns_3(self):
        assert _pad_width(999) == 3

    def test_end_1000_returns_4(self):
        assert _pad_width(1000) == 4

    def test_end_9999_returns_4(self):
        assert _pad_width(9999) == 4

    def test_end_10000_returns_5(self):
        assert _pad_width(10000) == 5


# ---------------------------------------------------------------------------
# _next_link
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestNextLink:
    def test_parses_next_rel(self):
        header = (
            '<https://api.github.com/repos/o/r/issues/1/comments?per_page=100&page=2>; rel="next", '
            '<https://api.github.com/repos/o/r/issues/1/comments?per_page=100&page=5>; rel="last"'
        )
        assert exp._next_link(header) == (
            "https://api.github.com/repos/o/r/issues/1/comments?per_page=100&page=2"
        )

    def test_no_next_rel_returns_none(self):
        header = (
            '<https://api.github.com/repos/o/r/issues/1/comments?per_page=100&page=1>; rel="first"'
        )
        assert exp._next_link(header) is None

    def test_empty_header_returns_none(self):
        assert exp._next_link("") is None


# ---------------------------------------------------------------------------
# _is_copilot_artifact
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestIsCopilotArtifact:
    def _comment(self, login: str, body: str) -> dict:
        return {"user": {"login": login}, "body": body, "id": 1, "html_url": ""}

    def test_bot_author_flagged(self):
        c = self._comment("github-actions[bot]", "some unrelated text")
        assert exp._is_copilot_artifact(c) is True

    def test_copilot_in_body(self):
        c = self._comment("alice", "This was generated by Copilot agent.")
        assert exp._is_copilot_artifact(c) is True

    def test_original_prompt_in_body(self):
        c = self._comment("bob", "Original prompt: do the thing")
        assert exp._is_copilot_artifact(c) is True

    def test_case_insensitive(self):
        c = self._comment("carol", "ORIGINAL REQUEST: fix bug")
        assert exp._is_copilot_artifact(c) is True

    def test_normal_comment_not_flagged(self):
        c = self._comment("dave", "LGTM, nice work!")
        assert exp._is_copilot_artifact(c) is False

    def test_missing_user_does_not_raise(self):
        c = {"user": None, "body": "hello", "id": 2, "html_url": ""}
        assert exp._is_copilot_artifact(c) is False


# ---------------------------------------------------------------------------
# _render_not_found
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestRenderNotFound:
    def test_contains_pr_number(self):
        md = exp._render_not_found(42)
        assert "PR #42" in md

    def test_contains_not_found_marker(self):
        md = exp._render_not_found(42)
        assert "404" in md or "not found" in md.lower()


# ---------------------------------------------------------------------------
# _render_pr (minimal smoke test)
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestRenderPr:
    def _make_pr(self, **overrides) -> dict:
        base = {
            "number": 7,
            "title": "Test PR",
            "html_url": "https://github.com/o/r/pull/7",
            "state": "open",
            "merged_at": None,
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2024-01-02T00:00:00Z",
            "body": "## Summary\n\nFixes things.",
            "base": {"ref": "main"},
            "head": {"ref": "feature/thing"},
            "merge_commit_sha": None,
        }
        base.update(overrides)
        return base

    def test_includes_title(self):
        md = exp._render_pr(self._make_pr(), [], [], True, True)
        assert "Test PR" in md

    def test_includes_pr_number(self):
        md = exp._render_pr(self._make_pr(), [], [], True, True)
        assert "PR #7" in md

    def test_empty_body_placeholder(self):
        md = exp._render_pr(self._make_pr(body=None), [], [], True, True)
        assert "_No PR description/body._" in md

    def test_merged_state(self):
        md = exp._render_pr(
            self._make_pr(state="closed", merged_at="2024-01-03T00:00:00Z"),
            [],
            [],
            True,
            True,
        )
        assert "merged" in md

    def test_copilot_section_present(self):
        md = exp._render_pr(self._make_pr(), [], [], True, True)
        assert "Copilot Artifacts" in md

    def test_copilot_match_surfaced(self):
        comments = [
            {
                "user": {"login": "github-actions[bot]"},
                "body": "Original prompt: do the thing",
                "id": 99,
                "html_url": "https://github.com/o/r/pull/7#issuecomment-99",
                "created_at": "2024-01-01T00:00:00Z",
            }
        ]
        md = exp._render_pr(self._make_pr(), comments, [], True, True)
        assert "github-actions[bot]" in md
        assert "Comment #99" in md

    def test_no_comments_section_when_disabled(self):
        md = exp._render_pr(self._make_pr(), [], [], False, False)
        assert "## Comments" not in md
        assert "## Review Comments" not in md
